
# update_fastlane

fastlane_version "2.35.1"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore")
    gym(scheme: "TestLocalization") # Build your app - more options available
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    snapshot
    gym(scheme: "TestLocalization") # Build your app - more options available
    deliver(force: true)
    frameit
  end

  desc "Take Snapshots"
  lane :snap do
    snapshot
    frameit
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    slack(
      message: "Successfully deployed new App Update."
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
